### ISSUE TITLE
Link quebrado

### ISSUE THREAD

**Issue by peddrogomes** [aHub-Tech/wildoverflow#34]
Na parte "How to use" do readme principal o link para os "mains commands" está quebrado, infelizmente não encontrei o link certo para concertar, mas vou deixar relatado aqui !

**Comment by vcwild** [comment]
Corrigido no commit [#33](https://github.com/vcwild/wildoverflow/commit/5b1fa4c9e147b45aaeedd5844be443179ee5df52)
