### ISSUE TITLE
Refatoracao: Deixar isso mais dinamico

### ISSUE THREAD

**Issue by caio-emidio** [aHub-Tech/wildoverflow#9]
Parece mto codigo repetido:
https://github.com/aHub-Tech/twitch-bot-wildoverflow/blob/main/twitch_bot/cogs/command_cog.py

Eh possivel colocar isso em DB ?

**Comment by vcwild** [comment]
Olá, agradeço a contribuição. 

Parte do problema foi solucionado, pois a implementação de mensagens já vem de banco de dados e é recebida via injeção da dependência `Messages`.

Sobre os comandos repetitivos, parte disso está na limitação da lib TwitchIO em obrigar cada comando a ter um método declarado. Uma solução muito mais elegante seria poder reaproveitar um mesmo comportamento para múltiplos comandos

Exemplo:

Como é:
```python
@commands.command(name='key', aliases=['alias_key_1', 'alias_key_2'])
    async def cmd_key(self, ctx):
        msg = self.messages.commands['MSG_KEY']\
            .format(ctx.author.name)
        await ctx.send(msg)
```

Como poderia ser:

```python
@commands.command(
    name=[qualquer comando dentro dessa lista de n comandos possíveis],
    aliases=[[aliases do comando 1], [aliases do comando 2], ..., [aliases do comando n])
    async def cmd_comportamento(self, ctx):
        msg = self.messages.commands['CHAVE_DB_BASEADA_NO_COMANDO_SOLICITADO']\
            .format(ctx.author.name)
        await ctx.send(msg)
```

Se sobrescritos, o parametro `name` poderia se comportar como uma lista e o parametro `aliases` como uma lista de listas.

E a melhor parte é que esses valores podem vir de um DB, o problema é que ainda não descobri como sobrescrever o comportamento da lib padrão...

**Comment by RodrigoDornelles** [comment]
Está bem engessado mesmo, custei a a me encontrar na estrutura, para poder fazer contribuições!
